import requests

BASE = "http://127.0.0.1:5000/api/v1"
# Test for input-0-json
print("_________START OF TEST NO 0_________")
response = requests.get(BASE +"/attack/vm-a211de")
print(response.json())
response = requests.get(BASE +"/attack/vm-c7bac01a07")
print(response.json())
print("_________END OF TEST NO 0_________")

# Test for input-1-json
print("_________START OF TEST NO 1_________")
response = requests.get(BASE +"/attack/vm-b8e6c350")
print(response.json())
response = requests.get(BASE +"/attack/vm-c1e6285f")
print(response.json())
response = requests.get(BASE +"/attack/vm-cf1f8621")
print(response.json())
response = requests.get(BASE +"/attack/vm-b462c04")
print(response.json())
response = requests.get(BASE +"/attack/vm-8d2d12765")
print(response.json())
response = requests.get(BASE +"/attack/vm-9cbedf7c66")
print(response.json())
response = requests.get(BASE +"/attack/vm-ae24e37f8a")
print(response.json())
response = requests.get(BASE +"/attack/vm-e30d5fa49a")
print(response.json())
response = requests.get(BASE +"/attack/vm-1b1cc9cd")
print(response.json())
response = requests.get(BASE +"/attack/vm-f270036588")
print(response.json())
print("_________END OF TEST NO 1_________")

# Test for input-2-json
print("_________START OF TEST NO 2_________")
response = requests.get(BASE +"/attack/vm-ec02d5c153")
print(response.json())
response = requests.get(BASE +"/attack/vm-a3ed2eed23")
print(response.json())
response = requests.get(BASE +"/attack/vm-2ba4d2f87")
print(response.json())
response = requests.get(BASE +"/attack/vm-b35b501")
print(response.json())
response = requests.get(BASE +"/attack/vm-7d1ff7af47")
print(response.json())
print("_________END OF TEST NO 2_________")

# Test for input-3-json
print("_________START OF TEST NO 3_________")
response = requests.get(BASE +"/attack/vm-9ea3998")
print(response.json())
response = requests.get(BASE +"/attack/vm-5f3ad2b")
print(response.json())
response = requests.get(BASE +"/attack/vm-d9e0825")
print(response.json())
response = requests.get(BASE +"/attack/vm-59574582")
print(response.json())
response = requests.get(BASE +"/attack/vm-f00923")
print(response.json())
response = requests.get(BASE +"/attack/vm-575c4a")
print(response.json())
response = requests.get(BASE +"/attack/vm-0c1791")
print(response.json())
response = requests.get(BASE +"/attack/vm-2987241")
print(response.json())
response = requests.get(BASE +"/attack/vm-ab51cba10")
print(response.json())
response = requests.get(BASE +"/attack/vm-a3660c")
print(response.json())
response = requests.get(BASE +"/attack/vm-864a94f")
print(response.json())
print("_________END OF TEST NO 3_________")